version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: school-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: school_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20
  adminer:
    image: adminer:4
    container_name: school-adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  db_data:




