services:
  - type: web
    name: school-management-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: your-mysql-host
      - key: DB_USER
        value: your-mysql-user
      - key: DB_PASSWORD
        value: your-mysql-password
      - key: DB_NAME
        value: your-mysql-database
